[project]
name = "bitcoin_monitor"
version = "0.0.0"
description = "Data engineering portfolio project"
requires-python = "3.13"
readme = "README.md"
#dependencies = ["requests>=2.28.0"]

#[tool.ruff]
#line-length = 88